[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dapp_solana = "AShmSyMtTNpdoTXEYJYq2ZLtchYyJSst7dNToRE8ivZk"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
